Name=input("what is your name:")
Gender=input("Write your genter male or female:")
Age=int(input("what is your age:"))
Phone_no=int(input("Enter your phone no:"))
Address=input("Enter your address:")
